<?php

namespace App\Command;

use App\Application\Services\Calendar\Connector\Connector;
use App\Application\Services\Calendar\Connector\Google\GoogleHandler;
use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class GoogleAuthTestCommand extends Command
{
    protected static $defaultName = 'app:google-auth-test';
    /**
     * @var UserRepository
     */
    private $userRepository;
    /**
     * @var Connector
     */
    private $connector;

    public function __construct(UserRepository $userRepository, Connector $connector, ?string $name = null)
    {
        parent::__construct($name);
        $this->userRepository = $userRepository;
        $this->connector = $connector;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
//        $user = (new User)->setEmail('valeriu.buzila@gmail.com');
//        $this->userRepository->persistAndFlush($user);

        $user = $this->userRepository->findOneBy(['email' => 'valeriu.buzila@gmail.com']);

        $service = 'google';

        if (!$this->connector->isRegistered($user, $service)) {
            $this->connector->register($user, $service);
        }

        $token = $this->connector->getAuthToken($user, $service);

        dump($token);

//        $this->google->handle($user);
    }
}