<?php

namespace App\Command;

use App\Application\Services\Calendar\Connector\Connector;
use App\Application\Services\Calendar\Fetch\Fetch;
use App\Application\Services\Security\GenerateToken;
use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class MsAuthTestCommand extends Command
{
    protected static $defaultName = 'app:ms-auth-test';
    /**
     * @var UserRepository
     */
    private $userRepository;
    /**
     * @var Connector
     */
    private $connector;
    /**
     * @var Fetch
     */
    private $fetch;

    public function __construct(UserRepository $userRepository, Connector $connector, Fetch $fetch, ?string $name = null)
    {
        parent::__construct($name);
        $this->userRepository = $userRepository;
        $this->connector = $connector;
        $this->fetch = $fetch;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
//        $user = (new User)->setEmail('valeriu.buzila@gmail.com');
//        $this->userRepository->persistAndFlush($user);

        $user = $this->userRepository->findOneBy(['email' => 'valeriu.buzila@gmail.com']);

        $service = 'outlook';

        if (!$this->connector->isRegistered($user, $service)) {
            $this->connector->register($user, $service);
        }

        $token = $this->connector->getToken($user, $service);

        dump($token);

        $calendars = $this->fetch->calendars($service, $token);
        dump($calendars);

        $freeBusy = $this->fetch->freeBusy($service, $token, new \DateTime(), (new \DateTime())->add(\DateInterval::createFromDateString('+20 days')), $calendars);
        dump($freeBusy);

        dump((new GenerateToken)());
    }
}
