<?php

namespace App\Command;

use App\Service\Calendar\Connector\Connector;
use App\Service\Calendar\Fetch\Fetch;
use App\Service\Security\GenerateToken;
use App\Entity\Account;
use App\Entity\AccountUser;
use App\Entity\User;
use App\Repository\AccountRepository;
use App\Repository\AccountUserRepository;
use App\Repository\UserRepository;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class MsAuthTestCommand extends Command
{
    protected static $defaultName = 'app:ms-auth-test';
    /**
     * @var UserRepository
     */
    private $userRepository;
    /**
     * @var Connector
     */
    private $connector;
    /**
     * @var Fetch
     */
    private $fetch;
    /**
     * @var AccountRepository
     */
    private $accountRepository;
    /**
     * @var AccountUserRepository
     */
    private $accountUserRepository;

    public function __construct(UserRepository $userRepository, AccountRepository $accountRepository, AccountUserRepository $accountUserRepository, Connector $connector, Fetch $fetch, ?string $name = null)
    {
        parent::__construct($name);
        $this->userRepository = $userRepository;
        $this->connector = $connector;
        $this->fetch = $fetch;
        $this->accountRepository = $accountRepository;
        $this->accountUserRepository = $accountUserRepository;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
//        $user = (new User)->setEmail('valeriu.buzila@gmail.com');
//        $account = (new Account)->setName('my account');
//        $accountUser = (new AccountUser)->setUser($user)->setAccount($account);
//
//        $this->accountRepository->persistAndFlush($account);
//        $this->userRepository->persistAndFlush($user);
//        $this->accountUserRepository->persistAndFlush($accountUser);

        $user = $this->userRepository->findOneBy(['email' => 'valeriu.buzila@gmail.com']);
        $accountUser = $user->getAccountUsers()[0];

        $service = 'outlook';

        if (!$this->connector->isRegistered($accountUser, $service)) {
            $this->connector->register($accountUser, $service);
        }

        $token = $this->connector->getToken($accountUser, $service);

        dump($token);

        $calendars = $this->fetch->calendars($service, $token);
        dump($calendars);

//        $freeBusy = $this->fetch->freeBusy($service, $token, new \DateTime(), (new \DateTime())->add(\DateInterval::createFromDateString('+20 days')), $calendars);
//        dump($freeBusy);

        $events = $this->fetch->events(
            $service,
            $token,
            new \DateTime(),
            (new \DateTime())->add(\DateInterval::createFromDateString('+20 days')),
            $calendars[0]->getCalendarId()
        );

        dump($events);

        dump((new GenerateToken)());
    }
}
