version: '3'

services:

    php-fpm:
        build: ./env/php-fpm/
        restart: always
        networks: 
            - calendar-net
        expose:
          - "9000"
        depends_on:
            - db
        links:
            - db
        volumes:
            - .:/var/www/
        
    nginx:
        build: ./env/nginx/
        restart: always
        networks: 
            - calendar-net
            - default
        ports:
#            - "80"
            - "443"
        depends_on:
            - db
            - php-fpm
        volumes:
            - .:/var/www/
            - ./env/nginx/conf.d/:/etc/nginx/conf.d/
            - ./env/nginx/snippets/:/etc/nginx/snippets/
            - ./env/nginx/ssl/:/etc/nginx/ssl/
        links:
            - php-fpm

    db:
        image: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: always
        volumes:
            - ./data/db:/var/lib/mysql
        networks: 
            - calendar-net
        environment:
            MYSQL_ROOT_PASSWORD: db_root_password 
            MYSQL_PASSWORD: calendar_pass
            MYSQL_DATABASE: calendar
            MYSQL_USER: calendar

#    migration:
#        image: nginx:latest
#        command: ["cd /var/www", "&&", "./bin/console", "make:migration", "-n"]
#        links:
#            - db
#            - nginx
#        depends_on:
#            - db
#            - nginx

networks:
    calendar-net: